//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by CodeSmith.
//
//     Date:    3/15/2011
//     Time:    4:50 PM
//     Version: 5.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Data.SqlTypes;
using System.Data.SqlClient;

namespace Blumen
{
    #region usp_Select_UserPermission Wrapper
    /// <summary>
    /// This class is a wrapper for the usp_Select_UserPermission stored procedure.
    /// </summary>
    public class SelectUserPermissionMaster
    {
        #region Member Variables
        protected string _connectionString = String.Empty;
        protected SqlConnection _connection = null;
        protected SqlTransaction _transaction = null;
        protected bool _ownsConnection = true;
        protected int _recordsAffected = -1;
        protected int _returnValue = 0;
        protected SqlString _userID = SqlString.Null;
        protected bool _userIDSet = false;
        protected SqlString _strMenuID = SqlString.Null;
        protected bool _strMenuIDSet = false;
        
        protected SqlString _companyID = SqlString.Null;
        protected bool _companyIDSet = false;
        #endregion

        #region Constructors
        public SelectUserPermissionMaster()
        {
        }

        public SelectUserPermissionMaster(string connectionString)
        {
            this.ConnectionString = connectionString;
        }

        public SelectUserPermissionMaster(SqlConnection connection)
        {
            this.Connection = connection;
        }

        public SelectUserPermissionMaster(SqlConnection connection, SqlTransaction transaction)
        {
            this.Connection = connection;
            this.Transaction = transaction;
        }
        #endregion

        #region Public Properties
        /// <summary>
        /// The connection string to use when executing the usp_Select_UserPermission stored procedure.
        /// </summary>
        public string ConnectionString
        {
            get { return _connectionString; }
            set { _connectionString = value; }
        }

        /// <summary>
        /// The connection to use when executing the usp_Select_UserPermission stored procedure.
        /// If this is not null, it will be used instead of creating a new connection.
        /// </summary>
        public SqlConnection Connection
        {
            get { return _connection; }
            set { _connection = value; }
        }

        /// <summary>
        /// The transaction to use when executing the usp_Select_UserPermission stored procedure.
        /// If this is not null, the stored procedure will be executing within the transaction.
        /// </summary>
        public SqlTransaction Transaction
        {
            get { return _transaction; }
            set { _transaction = value; }
        }

        /// <summary>
        /// Gets the return value from the usp_Select_UserPermission stored procedure.
        /// </summary>
        public int ReturnValue
        {
            get { return _returnValue; }
        }

        /// <summary>
        /// Gets the number of rows changed, inserted, or deleted by execution of the usp_Select_UserPermission stored procedure.
        /// </summary>
        public int RecordsAffected
        {
            get { return _recordsAffected; }
        }

        /// <summary>
        /// 
        /// </summary>
        public SqlString UserID
        {
            get { return _userID; }
            set
            {
                _userID = value;
                _userIDSet = true;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public SqlString strMenuID
        {
            get { return _strMenuID; }
            set
            {
                _strMenuID = value;
                _strMenuIDSet = true;
            }
        }

       

        /// <summary>
        /// 
        /// </summary>
        public SqlString companyID
        {
            get { return _companyID; }
            set
            {
                _companyID = value;
                _companyIDSet = true;
            }
        }
        #endregion

        #region Helper Methods
        private SqlConnection GetConnection()
        {
            if (this.Connection != null)
            {
                _ownsConnection = false;
                return this.Connection;
            }
            else
            {
                System.Diagnostics.Debug.Assert(this.ConnectionString.Length != 0, "You must first set the ConnectioString property before calling an Execute method.");
                return new SqlConnection(this.ConnectionString);
            }
        }
        #endregion

        #region Execute Methods
        /// <summary>
        /// This method calls the usp_Select_UserPermission stored procedure.
        /// </summary>
        public virtual void Execute()
        {
            SqlCommand cmd = new SqlCommand();

            SqlConnection cn = this.GetConnection();

            try
            {
                cmd.Connection = cn;
                cmd.Transaction = this.Transaction;
                cmd.CommandText = "[dbo].[usp_Select_UserPermissionMaster]";
                cmd.CommandType = CommandType.StoredProcedure;

                #region Populate Parameters
                SqlParameter prmReturnValue = cmd.Parameters.Add("@RETURN_VALUE", SqlDbType.Int);
                prmReturnValue.Direction = ParameterDirection.ReturnValue;

                SqlParameter prmUserID = cmd.Parameters.Add("@UserID", SqlDbType.VarChar);
                prmUserID.Direction = ParameterDirection.Input;
                prmUserID.Size = 50;
                if (_userIDSet == true || this.UserID.IsNull == false)
                {
                    prmUserID.Value = this.UserID;
                }

                SqlParameter prmstrMenuID = cmd.Parameters.Add("@strMenuID", SqlDbType.VarChar);
                prmstrMenuID.Direction = ParameterDirection.Input;
                prmstrMenuID.Size = 50;
                if (_strMenuIDSet == true || this.strMenuID.IsNull == false)
                {
                    prmstrMenuID.Value = this.strMenuID;
                }

                

                SqlParameter prmcompanyID = cmd.Parameters.Add("@companyID", SqlDbType.VarChar);
                prmcompanyID.Direction = ParameterDirection.Input;
                prmcompanyID.Size = 50;
                if (_companyIDSet == true || this.companyID.IsNull == false)
                {
                    prmcompanyID.Value = this.companyID;
                }
                #endregion

                #region Execute Command
                if (cn.State != ConnectionState.Open) cn.Open();
                _recordsAffected = cmd.ExecuteNonQuery();
                #endregion

                #region Get Output Parameters
                if (prmReturnValue.Value != null && prmReturnValue.Value != DBNull.Value)
                {
                    _returnValue = (int)prmReturnValue.Value;
                }

                #endregion
            }
            finally
            {
                if (_ownsConnection)
                {
                    if (cn.State == ConnectionState.Open)
                    {
                        cn.Close();
                    }

                    cn.Dispose();
                }
                cmd.Dispose();
            }
        }

        /// <summary>
        /// This method calls the usp_Select_UserPermission stored procedure.
        /// </summary>
        /// <param name="connectionString">The connection string to use</param>
        /// <param name="userID"></param>
        /// <param name="strMenuID"></param>
        /// <param name="strAction"></param>
        /// <param name="companyID"></param>
        public static void Execute(
        #region Parameters
string connectionString,
                SqlString userID,
                SqlString strMenuID,
                SqlString companyID
        #endregion
)
        {
            SelectUserPermissionMaster SelectUserPermissionMaster = new SelectUserPermissionMaster();

            #region Assign Property Values
            SelectUserPermissionMaster.ConnectionString = connectionString;
            SelectUserPermissionMaster.UserID = userID;
            SelectUserPermissionMaster.strMenuID = strMenuID;
            SelectUserPermissionMaster.companyID = companyID;
            #endregion

            SelectUserPermissionMaster.Execute();

            #region Get Property Values

            #endregion
        }
        #endregion

        /// <summary>
        /// This method calls the usp_SelectTB_Basic stored procedure and returns a DataSet with the results.
        /// </summary>
        /// <returns>DataSet</returns>
        public virtual DataSet ExecuteDataSet()
        {
            DataSet ds = new DataSet();
            SqlCommand cmd = new SqlCommand();

            SqlConnection cn = this.GetConnection();

            try
            {
                cmd.Connection = cn;
                cmd.Transaction = this.Transaction;
                cmd.CommandText = "[dbo].[usp_Select_UserPermissionMaster]";
                cmd.CommandType = CommandType.StoredProcedure;

                #region Populate Parameters
                SqlParameter prmReturnValue = cmd.Parameters.Add("@RETURN_VALUE", SqlDbType.Int);
                prmReturnValue.Direction = ParameterDirection.ReturnValue;

                SqlParameter prmUserID = cmd.Parameters.Add("@UserID", SqlDbType.VarChar);
                prmUserID.Direction = ParameterDirection.Input;
                prmUserID.Size = 50;
                if (_userIDSet == true || this.UserID.IsNull == false)
                {
                    prmUserID.Value = this.UserID;
                }

                SqlParameter prmstrMenuID = cmd.Parameters.Add("@strMenuID", SqlDbType.VarChar);
                prmstrMenuID.Direction = ParameterDirection.Input;
                prmstrMenuID.Size = 50;
                if (_strMenuIDSet == true || this.strMenuID.IsNull == false)
                {
                    prmstrMenuID.Value = this.strMenuID;
                }

                

                SqlParameter prmcompanyID = cmd.Parameters.Add("@companyID", SqlDbType.VarChar);
                prmcompanyID.Direction = ParameterDirection.Input;
                prmcompanyID.Size = 50;
                if (_companyIDSet == true || this.companyID.IsNull == false)
                {
                    prmcompanyID.Value = this.companyID;
                }
                #endregion

                #region Execute Command
                if (cn.State != ConnectionState.Open) cn.Open();

                SqlDataAdapter da = new SqlDataAdapter(cmd);
                da.Fill(ds);
                _recordsAffected = ds.Tables[0].Rows.Count;
                #endregion

                #region Get Output Parameters
                if (prmReturnValue.Value != null && prmReturnValue.Value != DBNull.Value)
                {
                    _returnValue = (int)prmReturnValue.Value;
                }

                #endregion
            }
            finally
            {
                if (_ownsConnection)
                {
                    if (cn.State == ConnectionState.Open)
                    {
                        cn.Close();
                    }

                    cn.Dispose();
                }
                cmd.Dispose();
            }

            return ds;
        }
        /// <summary>
        /// This method calls the usp_SelectTB_Basic stored procedure and returns a DataSet with the results.
        /// </summary>
        /// <param name="connectionString">The connection string to use</param>
        /// <param name="whereCondition"></param>
        /// <param name="orderByExpression"></param>
        /// <returns>DataSet</returns>
        public static DataSet ExecuteDataSet(
        #region Parameters
string connectionString,
                SqlString userID,
                SqlString strMenuID,
                SqlString companyID
        #endregion
)
        {
            SelectUserPermissionMaster SelectUserPermissionMaster = new SelectUserPermissionMaster();

            #region Assign Property Values
            SelectUserPermissionMaster.ConnectionString = connectionString;
            SelectUserPermissionMaster.UserID = userID;
            SelectUserPermissionMaster.strMenuID = strMenuID;
            SelectUserPermissionMaster.companyID = companyID;
            #endregion

            DataSet ds = SelectUserPermissionMaster.ExecuteDataSet();

            #region Get Property Values

            #endregion

            return ds;
        }
    }
    #endregion
}
