//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by CodeSmith.
//
//     Date:    6/2/2012
//     Time:    12:40 PM
//     Version: 5.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Data.SqlTypes;
using System.Data.SqlClient;

namespace Blumen
{
    #region usp_InsertBlumenSoft_UserLoginLog Wrapper
    /// <summary>
    /// This class is a wrapper for the usp_InsertBlumenSoft_UserLoginLog stored procedure.
    /// </summary>
    public class InsertBlumenSoftUserLoginLog
    {
        #region Member Variables
        protected string _connectionString = String.Empty;
        protected SqlConnection _connection = null;
        protected SqlTransaction _transaction = null;
        protected bool _ownsConnection = true;
        protected int _recordsAffected = -1;
        protected int _returnValue = 0;
        protected SqlInt32 _userID = SqlInt32.Null;
        protected bool _userIDSet = false;
        protected SqlDateTime _loginDate = SqlDateTime.Null;
        protected bool _loginDateSet = false;
        protected SqlDateTime _logOutDate = SqlDateTime.Null;
        protected bool _logOutDateSet = false;
        #endregion

        #region Constructors
        public InsertBlumenSoftUserLoginLog()
        {
        }

        public InsertBlumenSoftUserLoginLog(string connectionString)
        {
            this.ConnectionString = connectionString;
        }

        public InsertBlumenSoftUserLoginLog(SqlConnection connection)
        {
            this.Connection = connection;
        }

        public InsertBlumenSoftUserLoginLog(SqlConnection connection, SqlTransaction transaction)
        {
            this.Connection = connection;
            this.Transaction = transaction;
        }
        #endregion

        #region Public Properties
        /// <summary>
        /// The connection string to use when executing the usp_InsertBlumenSoft_UserLoginLog stored procedure.
        /// </summary>
        public string ConnectionString
        {
            get { return _connectionString; }
            set { _connectionString = value; }
        }

        /// <summary>
        /// The connection to use when executing the usp_InsertBlumenSoft_UserLoginLog stored procedure.
        /// If this is not null, it will be used instead of creating a new connection.
        /// </summary>
        public SqlConnection Connection
        {
            get { return _connection; }
            set { _connection = value; }
        }

        /// <summary>
        /// The transaction to use when executing the usp_InsertBlumenSoft_UserLoginLog stored procedure.
        /// If this is not null, the stored procedure will be executing within the transaction.
        /// </summary>
        public SqlTransaction Transaction
        {
            get { return _transaction; }
            set { _transaction = value; }
        }

        /// <summary>
        /// Gets the return value from the usp_InsertBlumenSoft_UserLoginLog stored procedure.
        /// </summary>
        public int ReturnValue
        {
            get { return _returnValue; }
        }

        /// <summary>
        /// Gets the number of rows changed, inserted, or deleted by execution of the usp_InsertBlumenSoft_UserLoginLog stored procedure.
        /// </summary>
        public int RecordsAffected
        {
            get { return _recordsAffected; }
        }

        /// <summary>
        /// 
        /// </summary>
        public SqlInt32 UserID
        {
            get { return _userID; }
            set
            {
                _userID = value;
                _userIDSet = true;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public SqlDateTime LoginDate
        {
            get { return _loginDate; }
            set
            {
                _loginDate = value;
                _loginDateSet = true;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public SqlDateTime LogOutDate
        {
            get { return _logOutDate; }
            set
            {
                _logOutDate = value;
                _logOutDateSet = true;
            }
        }
        #endregion

        #region Helper Methods
        private SqlConnection GetConnection()
        {
            if (this.Connection != null)
            {
                _ownsConnection = false;
                return this.Connection;
            }
            else
            {
                System.Diagnostics.Debug.Assert(this.ConnectionString.Length != 0, "You must first set the ConnectioString property before calling an Execute method.");
                return new SqlConnection(this.ConnectionString);
            }
        }
        #endregion

        #region Execute Methods
        /// <summary>
        /// This method calls the usp_InsertBlumenSoft_UserLoginLog stored procedure and returns a SqlDataReader with the results.
        /// </summary>
        /// <returns>SqlDataReader</returns>
        public virtual SqlDataReader Execute()
        {
            SqlDataReader reader = null;
            SqlCommand cmd = new SqlCommand();
            SqlConnection cn = this.GetConnection();

            try
            {
                cmd.Connection = cn;
                cmd.Transaction = this.Transaction;
                cmd.CommandText = "[dbo].[usp_InsertBlumenSoft_UserLoginLog]";
                cmd.CommandType = CommandType.StoredProcedure;

                #region Populate Parameters
                SqlParameter prmReturnValue = cmd.Parameters.Add("@RETURN_VALUE", SqlDbType.Int);
                prmReturnValue.Direction = ParameterDirection.ReturnValue;

                SqlParameter prmUserID = cmd.Parameters.Add("@UserID", SqlDbType.Int);
                prmUserID.Direction = ParameterDirection.Input;
                if (_userIDSet == true || this.UserID.IsNull == false)
                {
                    prmUserID.Value = this.UserID;
                }

                SqlParameter prmLoginDate = cmd.Parameters.Add("@LoginDate", SqlDbType.DateTime);
                prmLoginDate.Direction = ParameterDirection.Input;
                if (_loginDateSet == true || this.LoginDate.IsNull == false)
                {
                    prmLoginDate.Value = this.LoginDate;
                }

                SqlParameter prmLogOutDate = cmd.Parameters.Add("@LogOutDate", SqlDbType.DateTime);
                prmLogOutDate.Direction = ParameterDirection.Input;
                if (_logOutDateSet == true || this.LogOutDate.IsNull == false)
                {
                    prmLogOutDate.Value = this.LogOutDate;
                }
                #endregion

                #region Execute Command
                if (cn.State != ConnectionState.Open) cn.Open();
                if (_ownsConnection)
                {
                    reader = cmd.ExecuteReader(CommandBehavior.CloseConnection);
                }
                else
                {
                    reader = cmd.ExecuteReader();
                }
                #endregion

                #region Get Output Parameters
                if (prmReturnValue.Value != null && prmReturnValue.Value != DBNull.Value)
                {
                    _returnValue = (int)prmReturnValue.Value;
                }

                #endregion
            }
            finally
            {
                cmd.Dispose();
            }

            return reader;
        }

        /// <summary>
        /// This method calls the usp_InsertBlumenSoft_UserLoginLog stored procedure and returns a DataSet with the results.
        /// </summary>
        /// <returns>DataSet</returns>
        public virtual DataSet ExecuteDataSet()
        {
            DataSet ds = new DataSet();
            SqlCommand cmd = new SqlCommand();

            SqlConnection cn = this.GetConnection();

            try
            {
                cmd.Connection = cn;
                cmd.Transaction = this.Transaction;
                cmd.CommandText = "[dbo].[usp_InsertBlumenSoft_UserLoginLog]";
                cmd.CommandType = CommandType.StoredProcedure;

                #region Populate Parameters
                SqlParameter prmReturnValue = cmd.Parameters.Add("@RETURN_VALUE", SqlDbType.Int);
                prmReturnValue.Direction = ParameterDirection.ReturnValue;

                SqlParameter prmUserID = cmd.Parameters.Add("@UserID", SqlDbType.Int);
                prmUserID.Direction = ParameterDirection.Input;
                if (_userIDSet == true || this.UserID.IsNull == false)
                {
                    prmUserID.Value = this.UserID;
                }

                SqlParameter prmLoginDate = cmd.Parameters.Add("@LoginDate", SqlDbType.DateTime);
                prmLoginDate.Direction = ParameterDirection.Input;
                if (_loginDateSet == true || this.LoginDate.IsNull == false)
                {
                    prmLoginDate.Value = this.LoginDate;
                }

                SqlParameter prmLogOutDate = cmd.Parameters.Add("@LogOutDate", SqlDbType.DateTime);
                prmLogOutDate.Direction = ParameterDirection.Input;
                if (_logOutDateSet == true || this.LogOutDate.IsNull == false)
                {
                    prmLogOutDate.Value = this.LogOutDate;
                }
                #endregion

                #region Execute Command
                if (cn.State != ConnectionState.Open) cn.Open();

                SqlDataAdapter da = new SqlDataAdapter(cmd);
                da.Fill(ds);
                _recordsAffected = ds.Tables[0].Rows.Count;
                #endregion

                #region Get Output Parameters
                if (prmReturnValue.Value != null && prmReturnValue.Value != DBNull.Value)
                {
                    _returnValue = (int)prmReturnValue.Value;
                }

                #endregion
            }
            finally
            {
                if (_ownsConnection)
                {
                    if (cn.State == ConnectionState.Open)
                    {
                        cn.Close();
                    }

                    cn.Dispose();
                }
                cmd.Dispose();
            }

            return ds;
        }


        /// <summary>
        /// This method calls the usp_InsertBlumenSoft_UserLoginLog stored procedure and returns a SqlDataReader with the results.
        /// </summary>
        /// <param name="connectionString">The connection string to use</param>
        /// <param name="userID"></param>
        /// <param name="loginDate"></param>
        /// <param name="logOutDate"></param>
        /// <returns>SqlDataReader</returns>
    

        /// <summary>
        /// This method calls the usp_InsertBlumenSoft_UserLoginLog stored procedure and returns a DataSet with the results.
        /// </summary>
        /// <param name="connectionString">The connection string to use</param>
        /// <param name="userID"></param>
        /// <param name="loginDate"></param>
        /// <param name="logOutDate"></param>
        /// <returns>DataSet</returns>
        public static DataSet ExecuteDataSet(
        #region Parameters
string connectionString,
                SqlInt32 userID,
                SqlDateTime loginDate,
                SqlDateTime logOutDate
        #endregion
)
        {
            InsertBlumenSoftUserLoginLog insertBlumenSoftUserLoginLog = new InsertBlumenSoftUserLoginLog();

            #region Assign Property Values
            insertBlumenSoftUserLoginLog.ConnectionString = connectionString;
            insertBlumenSoftUserLoginLog.UserID = userID;
            insertBlumenSoftUserLoginLog.LoginDate = loginDate;
            insertBlumenSoftUserLoginLog.LogOutDate = logOutDate;
            #endregion

            DataSet ds = insertBlumenSoftUserLoginLog.ExecuteDataSet();

            #region Get Property Values

            #endregion

            return ds;
        }

        #endregion
    }
    #endregion
}
