//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by CodeSmith.
//
//     Date:    6/2/2012
//     Time:    1:09 PM
//     Version: 5.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Data.SqlTypes;
using System.Data.SqlClient;

namespace Blumen
{
    #region usp_UpdateBlumenSoft_UserLoginLog Wrapper
    /// <summary>
    /// This class is a wrapper for the usp_UpdateBlumenSoft_UserLoginLog stored procedure.
    /// </summary>
    public class UpdateBlumenSoftUserLoginLog
    {
        #region Member Variables
        protected string _connectionString = String.Empty;
        protected SqlConnection _connection = null;
        protected SqlTransaction _transaction = null;
        protected bool _ownsConnection = true;
        protected int _recordsAffected = -1;
        protected int _returnValue = 0;
        protected SqlInt64 _logAutoID = SqlInt64.Null;
        protected bool _logAutoIDSet = false;
        protected SqlDateTime _logOutDate = SqlDateTime.Null;
        protected bool _logOutDateSet = false;
        #endregion

        #region Constructors
        public UpdateBlumenSoftUserLoginLog()
        {
        }

        public UpdateBlumenSoftUserLoginLog(string connectionString)
        {
            this.ConnectionString = connectionString;
        }

        public UpdateBlumenSoftUserLoginLog(SqlConnection connection)
        {
            this.Connection = connection;
        }

        public UpdateBlumenSoftUserLoginLog(SqlConnection connection, SqlTransaction transaction)
        {
            this.Connection = connection;
            this.Transaction = transaction;
        }
        #endregion

        #region Public Properties
        /// <summary>
        /// The connection string to use when executing the usp_UpdateBlumenSoft_UserLoginLog stored procedure.
        /// </summary>
        public string ConnectionString
        {
            get { return _connectionString; }
            set { _connectionString = value; }
        }

        /// <summary>
        /// The connection to use when executing the usp_UpdateBlumenSoft_UserLoginLog stored procedure.
        /// If this is not null, it will be used instead of creating a new connection.
        /// </summary>
        public SqlConnection Connection
        {
            get { return _connection; }
            set { _connection = value; }
        }

        /// <summary>
        /// The transaction to use when executing the usp_UpdateBlumenSoft_UserLoginLog stored procedure.
        /// If this is not null, the stored procedure will be executing within the transaction.
        /// </summary>
        public SqlTransaction Transaction
        {
            get { return _transaction; }
            set { _transaction = value; }
        }

        /// <summary>
        /// Gets the return value from the usp_UpdateBlumenSoft_UserLoginLog stored procedure.
        /// </summary>
        public int ReturnValue
        {
            get { return _returnValue; }
        }

        /// <summary>
        /// Gets the number of rows changed, inserted, or deleted by execution of the usp_UpdateBlumenSoft_UserLoginLog stored procedure.
        /// </summary>
        public int RecordsAffected
        {
            get { return _recordsAffected; }
        }

        /// <summary>
        /// 
        /// </summary>
        public SqlInt64 LogAutoID
        {
            get { return _logAutoID; }
            set
            {
                _logAutoID = value;
                _logAutoIDSet = true;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public SqlDateTime LogOutDate
        {
            get { return _logOutDate; }
            set
            {
                _logOutDate = value;
                _logOutDateSet = true;
            }
        }
        #endregion

        #region Helper Methods
        private SqlConnection GetConnection()
        {
            if (this.Connection != null)
            {
                _ownsConnection = false;
                return this.Connection;
            }
            else
            {
                System.Diagnostics.Debug.Assert(this.ConnectionString.Length != 0, "You must first set the ConnectioString property before calling an Execute method.");
                return new SqlConnection(this.ConnectionString);
            }
        }
        #endregion

        #region Execute Methods
        /// <summary>
        /// This method calls the usp_UpdateBlumenSoft_UserLoginLog stored procedure.
        /// </summary>
        public virtual void Execute()
        {
            SqlCommand cmd = new SqlCommand();

            SqlConnection cn = this.GetConnection();

            try
            {
                cmd.Connection = cn;
                cmd.Transaction = this.Transaction;
                cmd.CommandText = "[dbo].[usp_UpdateBlumenSoft_UserLoginLog]";
                cmd.CommandType = CommandType.StoredProcedure;

                #region Populate Parameters
                SqlParameter prmReturnValue = cmd.Parameters.Add("@RETURN_VALUE", SqlDbType.Int);
                prmReturnValue.Direction = ParameterDirection.ReturnValue;

                SqlParameter prmLogAutoID = cmd.Parameters.Add("@LogAutoID", SqlDbType.BigInt);
                prmLogAutoID.Direction = ParameterDirection.Input;
                if (_logAutoIDSet == true || this.LogAutoID.IsNull == false)
                {
                    prmLogAutoID.Value = this.LogAutoID;
                }

                SqlParameter prmLogOutDate = cmd.Parameters.Add("@LogOutDate", SqlDbType.DateTime);
                prmLogOutDate.Direction = ParameterDirection.Input;
                if (_logOutDateSet == true || this.LogOutDate.IsNull == false)
                {
                    prmLogOutDate.Value = this.LogOutDate;
                }
                #endregion

                #region Execute Command
                if (cn.State != ConnectionState.Open) cn.Open();
                _recordsAffected = cmd.ExecuteNonQuery();
                #endregion

                #region Get Output Parameters
                if (prmReturnValue.Value != null && prmReturnValue.Value != DBNull.Value)
                {
                    _returnValue = (int)prmReturnValue.Value;
                }

                #endregion
            }
            finally
            {
                if (_ownsConnection)
                {
                    if (cn.State == ConnectionState.Open)
                    {
                        cn.Close();
                    }

                    cn.Dispose();
                }
                cmd.Dispose();
            }
        }

        /// <summary>
        /// This method calls the usp_UpdateBlumenSoft_UserLoginLog stored procedure.
        /// </summary>
        /// <param name="connectionString">The connection string to use</param>
        /// <param name="logAutoID"></param>
        /// <param name="logOutDate"></param>
        public static void Execute(
        #region Parameters
string connectionString,
                SqlInt64 logAutoID,
                SqlDateTime logOutDate
        #endregion
)
        {
            UpdateBlumenSoftUserLoginLog updateBlumenSoftUserLoginLog = new UpdateBlumenSoftUserLoginLog();

            #region Assign Property Values
            updateBlumenSoftUserLoginLog.ConnectionString = connectionString;
            updateBlumenSoftUserLoginLog.LogAutoID = logAutoID;
            updateBlumenSoftUserLoginLog.LogOutDate = logOutDate;
            #endregion

            updateBlumenSoftUserLoginLog.Execute();

            #region Get Property Values

            #endregion
        }
        #endregion
    }
    #endregion
}
