//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by CodeSmith.
//
//     Date:    6/16/2012
//     Time:    12:27 PM
//     Version: 5.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Data.SqlTypes;
using System.Data.SqlClient;

namespace Blumen
{
    #region SP_TB_InsertRolePermission Wrapper
    /// <summary>
    /// This class is a wrapper for the SP_TB_InsertRolePermission stored procedure.
    /// </summary>
    public class SPTBInsertRolePermission
    {
        #region Member Variables
        protected string _connectionString = String.Empty;
        protected SqlConnection _connection = null;
        protected SqlTransaction _transaction = null;
        protected bool _ownsConnection = true;
        protected int _recordsAffected = -1;
        protected int _returnValue = 0;
        protected SqlString _assignedTo = SqlString.Null;
        protected bool _assignedToSet = false;
        protected SqlString _userID = SqlString.Null;
        protected bool _userIDSet = false;
        protected SqlString _assignedBy = SqlString.Null;
        protected bool _assignedBySet = false;
        protected SqlString _splitter = SqlString.Null;
        protected bool _splitterSet = false;
        protected SqlString _cOMPANY_ID = SqlString.Null;
        protected bool _cOMPANY_IDSet = false;
        #endregion

        #region Constructors
        public SPTBInsertRolePermission()
        {
        }

        public SPTBInsertRolePermission(string connectionString)
        {
            this.ConnectionString = connectionString;
        }

        public SPTBInsertRolePermission(SqlConnection connection)
        {
            this.Connection = connection;
        }

        public SPTBInsertRolePermission(SqlConnection connection, SqlTransaction transaction)
        {
            this.Connection = connection;
            this.Transaction = transaction;
        }
        #endregion

        #region Public Properties
        /// <summary>
        /// The connection string to use when executing the SP_TB_InsertRolePermission stored procedure.
        /// </summary>
        public string ConnectionString
        {
            get { return _connectionString; }
            set { _connectionString = value; }
        }

        /// <summary>
        /// The connection to use when executing the SP_TB_InsertRolePermission stored procedure.
        /// If this is not null, it will be used instead of creating a new connection.
        /// </summary>
        public SqlConnection Connection
        {
            get { return _connection; }
            set { _connection = value; }
        }

        /// <summary>
        /// The transaction to use when executing the SP_TB_InsertRolePermission stored procedure.
        /// If this is not null, the stored procedure will be executing within the transaction.
        /// </summary>
        public SqlTransaction Transaction
        {
            get { return _transaction; }
            set { _transaction = value; }
        }

        /// <summary>
        /// Gets the return value from the SP_TB_InsertRolePermission stored procedure.
        /// </summary>
        public int ReturnValue
        {
            get { return _returnValue; }
        }

        /// <summary>
        /// Gets the number of rows changed, inserted, or deleted by execution of the SP_TB_InsertRolePermission stored procedure.
        /// </summary>
        public int RecordsAffected
        {
            get { return _recordsAffected; }
        }

        /// <summary>
        /// 
        /// </summary>
        public SqlString AssignedTo
        {
            get { return _assignedTo; }
            set
            {
                _assignedTo = value;
                _assignedToSet = true;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public SqlString UserID
        {
            get { return _userID; }
            set
            {
                _userID = value;
                _userIDSet = true;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public SqlString AssignedBy
        {
            get { return _assignedBy; }
            set
            {
                _assignedBy = value;
                _assignedBySet = true;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public SqlString Splitter
        {
            get { return _splitter; }
            set
            {
                _splitter = value;
                _splitterSet = true;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public SqlString COMPANY_ID
        {
            get { return _cOMPANY_ID; }
            set
            {
                _cOMPANY_ID = value;
                _cOMPANY_IDSet = true;
            }
        }
        #endregion

        #region Helper Methods
        private SqlConnection GetConnection()
        {
            if (this.Connection != null)
            {
                _ownsConnection = false;
                return this.Connection;
            }
            else
            {
                System.Diagnostics.Debug.Assert(this.ConnectionString.Length != 0, "You must first set the ConnectioString property before calling an Execute method.");
                return new SqlConnection(this.ConnectionString);
            }
        }
        #endregion

        #region Execute Methods
        /// <summary>
        /// This method calls the SP_TB_InsertRolePermission stored procedure.
        /// </summary>
        public virtual void Execute()
        {
            SqlCommand cmd = new SqlCommand();

            SqlConnection cn = this.GetConnection();

            try
            {
                cmd.Connection = cn;
                cmd.Transaction = this.Transaction;
                cmd.CommandText = "[dbo].[SP_TB_InsertRolePermission]";
                cmd.CommandType = CommandType.StoredProcedure;

                #region Populate Parameters
                SqlParameter prmReturnValue = cmd.Parameters.Add("@RETURN_VALUE", SqlDbType.Int);
                prmReturnValue.Direction = ParameterDirection.ReturnValue;

                SqlParameter prmAssignedTo = cmd.Parameters.Add("@AssignedTo", SqlDbType.NVarChar);
                prmAssignedTo.Direction = ParameterDirection.Input;
                prmAssignedTo.Size = -1;
                if (_assignedToSet == true || this.AssignedTo.IsNull == false)
                {
                    prmAssignedTo.Value = this.AssignedTo;
                }

                SqlParameter prmUserID = cmd.Parameters.Add("@UserID", SqlDbType.VarChar);
                prmUserID.Direction = ParameterDirection.Input;
                prmUserID.Size = 20;
                if (_userIDSet == true || this.UserID.IsNull == false)
                {
                    prmUserID.Value = this.UserID;
                }

                SqlParameter prmAssignedBy = cmd.Parameters.Add("@AssignedBy", SqlDbType.VarChar);
                prmAssignedBy.Direction = ParameterDirection.Input;
                prmAssignedBy.Size = 15;
                if (_assignedBySet == true || this.AssignedBy.IsNull == false)
                {
                    prmAssignedBy.Value = this.AssignedBy;
                }

                SqlParameter prmSplitter = cmd.Parameters.Add("@Splitter", SqlDbType.VarChar);
                prmSplitter.Direction = ParameterDirection.Input;
                prmSplitter.Size = 3;
                if (_splitterSet == true || this.Splitter.IsNull == false)
                {
                    prmSplitter.Value = this.Splitter;
                }

                SqlParameter prmCOMPANY_ID = cmd.Parameters.Add("@COMPANY_ID", SqlDbType.Char);
                prmCOMPANY_ID.Direction = ParameterDirection.Input;
                prmCOMPANY_ID.Size = 4;
                if (_cOMPANY_IDSet == true || this.COMPANY_ID.IsNull == false)
                {
                    prmCOMPANY_ID.Value = this.COMPANY_ID;
                }
                #endregion

                #region Execute Command
                if (cn.State != ConnectionState.Open) cn.Open();
                _recordsAffected = cmd.ExecuteNonQuery();
                #endregion

                #region Get Output Parameters
                if (prmReturnValue.Value != null && prmReturnValue.Value != DBNull.Value)
                {
                    _returnValue = (int)prmReturnValue.Value;
                }

                #endregion
            }
            finally
            {
                if (_ownsConnection)
                {
                    if (cn.State == ConnectionState.Open)
                    {
                        cn.Close();
                    }

                    cn.Dispose();
                }
                cmd.Dispose();
            }
        }

        /// <summary>
        /// This method calls the SP_TB_InsertRolePermission stored procedure.
        /// </summary>
        /// <param name="connectionString">The connection string to use</param>
        /// <param name="assignedTo"></param>
        /// <param name="userID"></param>
        /// <param name="assignedBy"></param>
        /// <param name="splitter"></param>
        /// <param name="cOMPANY_ID"></param>
        public static void Execute(
        #region Parameters
string connectionString,
                SqlString assignedTo,
                SqlString userID,
                SqlString assignedBy,
                SqlString splitter,
                SqlString cOMPANY_ID
        #endregion
)
        {
            SPTBInsertRolePermission sPTBInsertRolePermission = new SPTBInsertRolePermission();

            #region Assign Property Values
            sPTBInsertRolePermission.ConnectionString = connectionString;
            sPTBInsertRolePermission.AssignedTo = assignedTo;
            sPTBInsertRolePermission.UserID = userID;
            sPTBInsertRolePermission.AssignedBy = assignedBy;
            sPTBInsertRolePermission.Splitter = splitter;
            sPTBInsertRolePermission.COMPANY_ID = cOMPANY_ID;
            #endregion

            sPTBInsertRolePermission.Execute();

            #region Get Property Values

            #endregion
        }
        #endregion
    }
    #endregion
}
